project_id = "rnjpsjeqxgtnfgyqunfk"

[functions.evolution-webhook]
verify_jwt = false

[functions.search-leads]
verify_jwt = false

[functions.n8n-webhook-proxy]
verify_jwt = false

[functions.generate-copy]
verify_jwt = false

[functions.send-email]
verify_jwt = false
